apiVersion: v1
kind: Service
metadata:
  name: company
  labels:
    name: company
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: company